### PR TITLE
Fix older clients displaying nametags

### PR DESCRIPTION
**Pull request by LoneWolfHT**
I haven't tested this since I don't have an older client but it should work

### CODE REVIEW

**Comment by ClobberXD** [comment]
Commit(s) from your previous PR seem to have crept in. You can fix it like so:

- `git rebase HEAD~5 -i`
- Replace `pick` with `d` or `drop` for all irrelevant commits
- `Ctrl + X` --> `Y` --> `Enter`
- `git push LoneWolfHT master --force`

To avoid this in the future, please leave the master branch untouched, and make separate branches from master for each PR.

**Comment by ClobberXD** [comment]
Also, this feels like a hack. A better fix would be to disallow older clients, as they're supposed to use 0.4.16+ anyway.

**Comment by LoneWolfHT** [comment]
Ok I think it's good now

**Comment by krypticbit** [comment]
A globalstep is hardly the right way to do this, and I've already blocked older clients.

**Pull request closed without merging**
